### PR TITLE
Feature/texture support

### PR DESCRIPTION
**Pull request by micahpearlman**
Added some vgu methods to support slightly easier text rendering

### CODE REVIEW

**Comment by micahpearlman** [comment]
> pow!! ;)

@renanyoy lol.  I'm going through and doing a big refactor.  vulkan support hopefully sooner then later.

**Comment by renanyoy** [comment]
I've returned back to my old codes too, 2D,3d engine in swift, metal/vulkan, for making a new sound synced video mixer app ;) work in progress.. I was using monkVG in my xamarin openGL UI framework.. maybe would be nice to split the vg part and the vulkan renderer, with some generic command buffer.. so it would be kinda platform agnostic.. vulkan, metal, directX..

**Comment by micahpearlman** [comment]
Oh the generic command buffer thing sounds interesting 🤔 Anyone else implement something like this or do you have further details on how you would implement something like this?  Would be great to collaborate a bit!  On Oct 11, 2024, at 4:01 PM, renan jegouzo ***@***.***> wrote:﻿
I've returned back to my old codes too, 2D,3d engine in swift, metal/vulkan, for making a new sound synced video mixer app ;) work in progress.. I was using monkVG in my xamarin openGL UI framework.. maybe would be nice to split the vg part and the vulkan renderer, with some generic command buffer.. so it would be kinda platform agnostic.. vulkan, metal, directX..

**Comment by renanyoy** [comment]
I have made some things in swift, the generic part is my own abstraction layer, with main target metal.
https://github.com/aestesis/Aether/blob/master/Sources/Aether/Foundation/Path.swift
the VG part is pretty basic

as lib for the first part, I have made a metal like API targeting Vulkan 
https://github.com/aestesis/Uridium/blob/master/Sources/Uridium/Tin.swift
but this part isn't finished yet

you can also look at the flutter rendering engine, it works everywhere
https://github.com/flutter/engine/blob/main/impeller/README.md

I hope, it can provide you some general ideas

**Pull request merged**
